name: Bug
description: File a Twilio Conversations iOS SDK bug report
title: "Bug: [PROVIDE A SHORT SUMMARY]"
labels: ["bug", "triage"]
assignees:
  - berkus
body:
  - type: input
    id: version
    attributes:
      label: SDK version
      description: Version of Conversations SDK where this bug reproduces, could be multiple versions, comma-separated
      placeholder: "[ENTER SDK VERSION HERE]"
    validations:
      required: true
  - type: input
    id: model
    attributes:
      label: Device model
      description: Model of iOS or Mac device where this issue reproduces
      placeholder: "[ENTER iPhone/iPad/Mac MODEL HERE]"
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS version
      description: Version of operating system where this issue reproduces
      placeholder: "[ENTER YOUR DEVICE IOS VERSION HERE/OSX VERSION FOR Mac]"
    validations:
      required: false
  - type: textarea
    id: problem
    attributes:
      label: Issue description
      placeholder: Describe the problem, providing crash stack traces if this is a crash.
